name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Build Docker images
        #run: docker-compose build

      - name: Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint testing
        run: docker-compose run --rm app sh -c "flake8"
