name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Debug: Confirm runner is alive
        run: echo "✅ Runner is alive and workflow started."

      - name: 🧪 Debug: Show Docker version
        run: docker version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose build

      - name: 🧪 Debug: List Docker images
        run: docker images

      - name: Run Tests (with timeout)
        run: timeout 300 docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter (with timeout)
        run: timeout 120 docker-compose run --rm app sh -c "flake8"
